#!/bin/bash

[ -z "$1" ] && echo "error: missing task." && exit 5;
[ -z "$2" ] && echo "error: missing port." && exit 5;

r="^([^:]*)(:([0-9]+))?$" && [[ "$3" =~ $r ]] && h="${BASH_REMATCH[1]}" && p="${BASH_REMATCH[3]}"
HOST=${h:-localhost}
PORT=${p:-10022}
USER=${4:-backdoor}

case ${1} in
    open) ssh -p ${PORT} backdoor@${HOST} "backdoor link ${2} ${USER}" ;;
    bind) ssh -R ${2}:localhost:${PORT} -p ${PORT} ${USER}@${HOST} ;;
    link) ssh -p ${2} -l ${USER} localhost ;;
    *) echo "backdoor documentation at https://github.com/javanile/backdoor" ;;
esac
