version: '3.3'

services:
  backdoor:
    build: ./
    networks:
      backdoor:
        ipv4_address: 10.0.22.254
    ports:
      - '10022:10022'

networks:
  backdoor:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'true'
    ipam:
      driver: default
      config:
        - subnet: 10.0.22.0/24
