##
# javanile/backdoor (v0.0.1)
# Reverse SSH tunnel for Docker
##

version: '3.3'

services:
  server:
    build: ./
    networks:
      backdoor:
        ipv4_address: 10.0.22.254
    ports:
      - '10022:10022'

  target:
    build: ./
    networks:
      backdoor:
        ipv4_address: 10.0.22.253
    environment:
      - BACKDOOR_HOST=server
      - BACKDOOR_BIND=50001
    links:
      - server

  client:
    build: ./
    networks:
      backdoor:
        ipv4_address: 10.0.22.252
    environment:
      - BACKDOOR_HOST=server
      - BACKDOOR_OPEN=50001
    links:
      - target

networks:
  backdoor:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'true'
    ipam:
      driver: default
      config:
        - subnet: 10.0.22.0/24
