#!/bin/bash

##
# javanile/backdoor (v0.0.1)
# Reverse SSH tunnel for Docker
##

set -e

FILE=/usr/local/bin/backdoor

curl -o ${FILE} https://javanile.github.io/backdoor/backdoor
chmod +x ${FILE}

echo "backdoor installed on '${FILE}'."
